* ~eeg-visualizer-0~

A real-time visualizer for EEG data.

Main use case, currently: Receive EEG data via
[[https://labstreaminglayer.org][LSL]] and visualize for neurofeedback.

This is a toy project and by no means "complete" or "production-ready" in any
way.

** Dependencies

- [[https://github.com/sccn/liblsl][liblsl]]
- [[https://www.fftw.org][FFTW]]
- [[https://www.sfml-dev.org][SFML]]

Plus [[https://cmake.org][CMake]] and optionally
[[https://ninja-build.org][Ninja]] for building.

** Build instructions

#+begin_src sh
  mkdir -p build; cd build
  cmake ..
  make
#+end_src

Debug build for development:
#+begin_src sh
  mkdir -p build; cd build
  cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug
  cd ..
  ninja -C build
#+end_src

** Silencing LSL info messages

By default, the LSL library prints info messages e.g. when connecting to the
network. This can be configured via a configuration file, which can be created
as follows:

#+begin_src sh
mkdir -p $HOME/lsl_api && printf "[log]\nlevel = -2" > $HOME/lsl_api/lsl_api.cfg
#+end_src

Caution: If a configuration file already exists at ~$HOME/lsl_api~, it will be
overwritten by the above command. There are multiple possible locations for LSL
configuration files. It is recommended to use the same configuration on all
servers and clients on a network. Also see the [[https://labstreaminglayer.readthedocs.io/info/lslapicfg.html?highlight=log#configuration-file-locations][LSL documentation]].
